---
name: Ilona Maskova # Ваше имя
job: QA Engineer
level: junior
email: ilona@hexlet.io
description: |

skills: 
  - Функциональное тестирование
  - Написание багрепортов
  - Linux
  - Слепая печать
  - Английский язык C1
