---
functional:
  - Требование 3
  - Требование 4
  - Требование 8
  - Требование 9
  - Требование 10
  - Требование 11
  - Требование 12
non-functional:
  - Требование 1
  - Требование 2
  - Требование 5
  - Требование 6
  - Требование 7
implicit:
Сайт должен обеспечивать удобство использования и комфортную навигацию.
Корзина товаров должна сохраняться в сессии браузера и быть доступной даже после закрытия страницы.
Интерфейс должен подстраиваться под любое современное устройство и браузер
