- summary: |
    Вход пользователя с правильными учетными данными
  requirement: |
    При введении существующих логина и пароля пользователь успешно входит в систему
  prerequisites: |
    Открыть страницу входа
  test-data: |
    Логин = ilona
    Пароль = password
  steps:
    - Ввести логин 'ilona'
    - Ввести пароль 'password'
    - Нажать кнопку «Войти»
  expected-result: |
    Пользователь попадает на домашнюю страницу системы

- summary: |
    Попытка входа с неправильными учетными данными
  requirement: |
    Если введены неверные логин или пароль, система должна вывести сообщение об ошибке
  prerequisites: |
    Открыть страницу входа
  test-data: |
    Логин = hexlet
    Пароль = badpass
  steps:
    - Ввести логин 'hexlet'
    - Ввести пароль 'badpass'
    - Нажать кнопку «Войти»
  expected-result: |
    Отображается сообщение об ошибке («Неверный логин или пароль») и остается на странице входа
